services:
  postgres:
    image: postgres:16-alpine
    container_name: good_job_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: good_job_cache
    networks:
      - cache_network

  minio:
    image: minio/minio
    container_name: good_job_storage
    command: server /data --console-address ":9001"
    ports:
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - storage_data:/data
    networks:
      - storage_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: good_job_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/app/apps/api/src
      - ./prisma:/app/apps/api/prisma
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - db_network
      - cache_network
      - storage_network

volumes:
  db_data:
  storage_data:

networks:
  db_network:
    driver: bridge
  cache_network:
    driver: bridge
  storage_network:
    driver: bridge
